[project]
name = "wavey2"
version = "0.0.0" # Placeholder; version is tracked in `js/version.js`
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4",
    "numpy",
    "pygrib",
    "requests",
]

[dependency-groups]
dev = [
    "mypy",
    "ruff",
    "types-requests",
]

[tool.mypy]
python_version = "3.14"
strict = true
disallow_any_generics = false
disallow_untyped_calls = false

[[tool.mypy.overrides]]
module = [
    "pygrib",
]
ignore_missing_imports = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I"]
